---
title: "Case I - modelling Danish fire insurance data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MGL-regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## MGL and MGL-EV copulas of Zhnegxiao Li et al.(2021)


This example implements the MGL and MGL-EV copulas of Zhengxiao Li et al. (2021, “MGL copulas”).

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


### read the danish data set

```{r setup}
  library(rMGLReg)
  library(fitdistrplus)
  library(splines)
  data("danishmulti")
  dt <- data.table::data.table(danishmulti)
  dt[, year := as.numeric(substr(Date, start = 1, stop = 4))]
  dtnew <- dt[Building>0&Contents>0]
  y1 <- dtnew$Building
  y2 <- dtnew$Contents
  
  XY <- cbind(y1, y2)
  y <- cbind(y1, y2)
  m1 <- sROC::kCDF(y[,1], bw = 0.2, xgrid = sort(y[,1]))
  m2 <- sROC::kCDF(y[,2], bw = 0.2, xgrid = sort(y[,2]))
  x <- cbind(m1$x, m2$x)
  u1 <- m1$Fhat;y1 <- y[,1]
  u1[order(y1)] <- m1$Fhat
  u2 <- m2$Fhat; y2 <- y[,2]
  u2[order(y2)] <- m2$Fhat
  U <- cbind(u1, u2) # empirical cdf
  Usample <- U

```


```{r}
library(ggplot2)
library(latex2exp)
newtheme <-   theme_bw() + theme(axis.line = element_line(colour = "black"),
                                 axis.text.x = element_text(margin = margin(t = 0.25, unit = "cm")),
                                 axis.text.y = element_text(margin = margin(r = 0.25, unit = "cm"),
                                                            size = 10, 
                                                            vjust = 0.5, 
                                                            hjust = 0.5),
                                 axis.ticks.length = unit(-0.1, "cm"),
                                 plot.title = element_text(hjust = 0.5),
                                 legend.direction = 'vertical',
                                 legend.position = c(.95, .99),
                                 legend.justification = c("right", "top"),
                                 legend.box.just = "right",
                                 legend.text = element_text(size = 10)) 

dtplot <- data.frame(U1 = Usample[,1], U2 = Usample[,2],
                     logY1 = log(XY[,1]), logY2 = log(XY[,2]))

p1 <- ggplot(data = dtplot, mapping = aes(y = logY1, 
                                          x = logY2)) + 
  newtheme +
  geom_point() + 
  labs(title = "", 
       x = TeX("$log Y_1$"), 
       y = TeX("$log Y_2$")) +  
  scale_x_continuous(limits = c(-7.5, 5),
                     breaks = seq(-7.5, 5, by = 2.5)) +
  scale_y_continuous(limits = c(-5, 5),
                     breaks = seq(-5, 5, by = 2.5))

p1

p2 <- ggplot(data = dtplot, mapping = aes(y = U2, 
                                           x = U1)) + 
  newtheme +
  geom_point() + 
  labs(title = "", 
     x = TeX("$u_1$"), 
     y = TeX("$u_2$")) +  
  scale_x_continuous(limits = c(0, 1),
                     breaks = seq(0, 1, by = 0.2)) +
  scale_y_continuous(limits = c(0, 1),
                     breaks = seq(0, 1, by = 0.2))

p2
library(patchwork)
p0 <- p1 + p2 + plot_layout(ncol = 2)
p0

```


<!-- ### fitting copulas withtout covariates -->

<!-- ```{r} -->
<!--   X <- model.matrix( ~ 1, data = dtnew) -->

<!--   # survival MGL copual regression -->
<!--   m.MGL180 <- MGL.reg(U = U, copula = "MGL180", -->
<!--                                  method = "Brent", -->
<!--                                  lower = -5, upper = 5, -->
<!--                                  X = X, -->
<!--                                  control = list(maxit = 100000, -->
<!--                                                 fnscale = -1), -->
<!--                                  initpar = c(0.01) -->
<!--   ) -->
<!--   # survival MGL-EV copual regression -->
<!--   m.MGLEV180 <- MGL.reg(U = U, copula = "MGL-EV180", -->
<!--                          method = "Brent", -->
<!--                         lower = -5, upper = 5, -->
<!--                          X = X, -->
<!--                          control = list(maxit = 100000, -->
<!--                                         fnscale = -1), -->
<!--                          initpar = c(0.01) -->
<!--   ) -->
<!--   # survival MGL-EV copual regression -->
<!--   m.gumbel <- MGL.reg(U = U, copula = "Gumbel", -->
<!--                          method = "Brent", -->
<!--                          lower = -5, upper = 5, -->
<!--                          X = X, -->
<!--                          control = list(maxit = 100000, -->
<!--                                         fnscale = -1), -->
<!--                          initpar = c(0.01) -->
<!--   ) -->
<!--   # show the estimates and stardard errors for the models -->
<!--   modout <- function(m) { -->
<!--     Hessian <- -m$hessian -->
<!--     se <- sqrt(diag(solve(Hessian)))                  ## stardard error -->
<!--     Z <- m$par/se                                             ##  Z statistic -->
<!--     p <- ifelse(Z>=0, pnorm(Z, lower=F)*2, pnorm(Z)*2)           ## p value -->
<!--     summarytable <- data.frame(m$par, se, Z, p) -->
<!--     LL <- m$value -->
<!--     NLL <- -m$value  # - loglikelihood value -->
<!--     AIC <- 2*length(m$par) + 2*NLL -->
<!--     BIC <- log(nrow(U))*length(m$par) + 2*NLL -->
<!--     list(summary = summarytable, ll =  m$value, AIC = AIC, BIC = BIC) -->
<!--   } -->

<!--   estimates.copula <- c(exp(m.MGL180$par), exp(m.MGLEV180$par), exp(m.gumbel$par) + 1) -->
<!--   sd.copula <- c(sqrt(-1/m.MGL180$hessian)*exp(m.MGL180$par), sqrt(-1/m.MGLEV180$hessian)*exp(m.MGLEV180$par), sqrt(-1/m.gumbel$hessian)*exp(m.gumbel$par)) -->
<!--   ll.copula <- c(modout(m.MGL180)$ll, modout(m.MGLEV180)$ll, modout(m.gumbel)$ll) -->
<!--   AIC.copula <- c(modout(m.MGL180)$AIC, modout(m.MGLEV180)$AIC, modout(m.gumbel)$AIC) -->
<!--   BIC.copula <- c(modout(m.MGL180)$BIC, modout(m.MGLEV180)$BIC, modout(m.gumbel)$BIC) -->

<!--   table1 <- cbind(estimates.copula, sd.copula, ll.copula, AIC.copula, BIC.copula) -->
<!--   row.names(table1) <- c('MGL', 'survival MGL', 'Gumbel') -->
<!--   knitr::kable(table1, digits = 3) -->
<!-- ``` -->


### survival MGL copual and survival MGL-EV regression
```{r}
  dtnew[, x1 := (year - mean(year))/(sd(year))]
  dtnew[, day := difftime(as.Date(Date), as.Date("1980-01-03"), units="days")]

  X <- splines::ns(dtnew$year, knots = quantile(dtnew$year, c(0.5)), intercept = T)
```


```{r }
  # survival MGL copual regression
  m.MGL180 <- MGL.reg(U = U, copula = "MGL180",
                                 method = "Nelder-Mead",
                                 X = X,
                                 control = list(maxit = 100000,
                                                fnscale = -1),
                                 initpar = c(-0.32, 0.001, 0.001)
  )
  # survival MGL-EV copual regression
  m.MGLEV180 <- MGL.reg(U = U, copula = "MGL-EV180",
                         method = "Nelder-Mead",
                         X = X,
                         control = list(maxit = 100000,
                                        fnscale = -1),
                         initpar = c(-0.32, 0.001, 0.001)
  )
  # gumbel regression
  m.gumbel <- MGL.reg(U = U, copula = "Gumbel",
                         method = "Nelder-Mead",
                         X = X,
                         control = list(maxit = 100000,
                                        fnscale = -1),
                         initpar = c(-0.32, 0.001, 0.001)
  )
  
```


### The predicted value of copula parameter with different value of the covariate \textit{Year} for the Danish fire insurance data set.
```{r }
# Survival MGL regression model
par.est <- m.MGL180$par
agepred <- seq(from = 1980, to = 1990)
Xcopula <-  splines::ns(agepred, knots = quantile(dtnew$year, c(0.5)), intercept = T)
delta.est <- exp(Xcopula%*%par.est)
cov.est <- -solve(m.MGL180$hessian)
beta.sim <- matrix(0, nrow = 100, ncol = 4)
delta.mat <- matrix(0, nrow = length(agepred), ncol = 100)
beta.sim <- mvrnorm(100, mu = par.est, Sigma = cov.est)
for(i in 1:100){
  delta.mat[,i] <- exp(Xcopula%*%beta.sim[i,])
}
matplot(delta.mat, col = 'gray', type = 'l', ylim = c(0, 2), main = 'Survival MGL')
lines(delta.est, col = 'red', lwd = 2)


# Surivial MGL-EV regression
par.est <- m.MGLEV180$par
agepred <- seq(from = 1980, to = 1990)
Xcopula <-  ns(agepred, knots = quantile(dtnew$year, c(0.5)), intercept = T)
delta.est <- exp(Xcopula%*%par.est)
cov.est <- -solve(m.MGLEV180$hessian)
beta.sim <- matrix(0, nrow = 100, ncol = 4)
delta.mat <- matrix(0, nrow = length(agepred), ncol = 100)
beta.sim <- mvrnorm(100, mu = par.est, Sigma = cov.est)
for(i in 1:100){
  delta.mat[,i] <- exp(Xcopula%*%beta.sim[i,])
}
matplot(delta.mat, col = 'gray', type = 'l', ylim = c(0, 2), main = 'Survival MGL-EV')
lines(delta.est, col = 'red', lwd = 2)

# Gumbel regression
par.est <- m.gumbel$par
delta.est <- exp(Xcopula%*%par.est) + 1

cov.est <- -solve(m.gumbel$hessian)
beta.sim <- matrix(0, nrow = 100, ncol = 4)
delta.mat <- matrix(0, nrow = length(agepred), ncol = 100)
beta.sim <- mvrnorm(100, mu = par.est, Sigma = cov.est)
for(i in 1:100){
  delta.mat[,i] <- exp(Xcopula%*%beta.sim[i,]) + 1
}
matplot(delta.mat, col = 'gray', type = 'l', ylim = c(0, 2), main = 'Gumbel')
lines(delta.est, col = 'red', lwd = 2)


```
